
spring:
  config:
    activate:
      on-profile: common
  # H2 콘솔을 기본적으로 비활성화
  h2:
    console:
      enabled: false
  # 타임리프 설정
  thymeleaf:
    servlet:
      produce-partial-output-while-processing: false
  # JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
    #        show_sql: true // System.out에 출력
        dialect: org.hibernate.dialect.MySQL8Dialect
      # ddl-auto와 같이 각 환경에 따라 달라져야 하는 설정은 공통 파일(application-common.yml)에서 관리하지 않는 것이 좋습니다.
      naming:
        physical-strategy: com.mysite.jpa_shoppingmall.config.CamelCaseToSnakeAndUpperCaseStrategy

  # 이미지 파일 등록 설정
  servlet:
    multipart:
      max-file-size: 20MB # 파일 한 개당 최대 사이즈 (모든 환경 공통)
      max-request-size: 100MB # 요청당 최대 파일 크기 (모든 환경 공통)