
spring:
  config:
    activate:
      on-profile: profile1

  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/shop_dev?serverTimezone=%2B09:00
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  # 개발 환경에서는 캐싱 기능을 꺼둔다.
  thymeleaf:
    cache: false

  # JPA
  jpa:
    hibernate:
      ddl-auto: create

# 파일 저장 경로(로컬 서버 내부용)
item:
  imgLocation: C:/shop/item

# 개발 환경인 Windows의 일반적인 업로드 경로
upload:
  path: C:/shop/item