spring:
  config:
    activate:
      on-profile: profile2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ✅ 'Asia/Seoul'을 '+09:00'으로 변경
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=%2B09:00
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create # 실제 배포할 때 none으로 설정됬는지 반드시 확인할 것!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # 운영 환경에서는 캐싱 기능을 켜둔다.
  thymeleaf:
    cache: true

