

spring:
  config:
    activate:
      on-profile: common
  # H2 콘솔을 기본적으로 비활성화
  h2:
    console:
      enabled: false
  # 타임리프 설정
  thymeleaf:
    servlet:
      produce-partial-output-while-processing: false

  # JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
    #        show_sql: true // System.out에 출력
    hibernate:
      # ddl-auto와 같이 각 환경에 따라 달라져야 하는 설정은 공통 파일(application-common.yml)에서 관리하지 않는 것이 좋습니다.
      naming:
        physical-strategy: com.mysite.jpa_shoppingmall.config.CamelCaseToSnakeAndUpperCaseStrategy