
spring:
  config:
    activate:
      on-profile: profile1
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  # 개발 환경에서는 캐싱 기능을 꺼둔다.
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect